"""
Job Processors

BACKWARD COMPATIBILITY LAYER
----------------------------
This module re-exports all processor classes from the new modular structure
for backward compatibility with existing code that imports from here.

New code should import directly from services.processors instead.

.. deprecated::
    This module will be removed in a future version.
    Use ``from services.processors import ...`` instead.
"""

import warnings

warnings.warn(
    "Import from services.processors instead of services.job_processors. "
    "This module will be removed in a future version.",
    DeprecationWarning,
    stacklevel=2,
)

from services.processors import (
    BaseJobProcessor,
    VideoOutputHandler,
    AudioOutputHandler,
    ImageOutputHandler,
    ComfyUIProcessor,
    WAN22TextToVideoJobProcessor,
    WAN22ImageToVideoJobProcessor,
    ImageToVideoFromLastFrameJobProcessor,
    WAN22TextToVideoWan2GPProcessor,
    WAN22ImageToVideoWan2GPProcessor,
    ImageToVideoFromLastFrameWan2GPProcessor,
    LTX23TextToVideoWan2GPProcessor,
    LTX23ImageToVideoWan2GPProcessor,
    LTX2TrainerI2VLoraProcessor,
    LTX2PipelinesI2VLoraProcessor,
    LTX2PipelinesTextToVideoProcessor,
    VideoUpscalerJobProcessor,
    SparkVSRUpscalerJobProcessor,
    TurboDiffusionT2VJobProcessor,
    TurboDiffusionI2VJobProcessor,
    DreamIDOmniImageToVideoProcessor,
    StableAudioJobProcessor,
    AudioXJobProcessor,
    VibeVoiceJobProcessor,
    VibeVoiceMultiCloneJobProcessor,
    DiffRhythmCLIJobProcessor,
    ChatterboxTTSJobProcessor,
    ChatterboxVoiceCloneJobProcessor,
    TextToImageJobProcessor,
    ZImageTextToImageProcessor,
    ZImageControlNetProcessor,
    ZImageInpaintProcessor,
    QwenImageEditProcessor,
    QwenImageInpaintProcessor,
    QwenImageT2IProcessor,
    QwenImage2512LoraT2IProcessor,
    LLMJobProcessor,
    HeartMuLaCLIJobProcessor,
    AceStepCLIJobProcessor,
    Qwen3TTSJobProcessor,
    Qwen3VoiceDesignJobProcessor,
    Qwen3VoiceCloneJobProcessor,
    F5TTSJobProcessor,
    F5VoiceCloneJobProcessor,
    WavTTSJobProcessor,
    WavTTSVoiceCloneJobProcessor,
    DotsTTSJobProcessor,
    DotsTTSVoiceCloneJobProcessor,
    ScenemaAudioTTSProcessor,
    ScenemaAudioVoiceCloneProcessor,
    DramaboxTTSProcessor,
    DramaboxVoiceCloneProcessor,
    QwenImageEditTurboProcessor,
    QwenImageInpaintTurboProcessor,
    QwenImageT2ITurboProcessor,
    FluxKontextEditProcessor,
    FluxKontextT2IProcessor,
    Krea2TextToImageProcessor,
    AnimaTextToImageProcessor,
    MMAudioJobProcessor,
    LavaSRJobProcessor,
    PrismAudioJobProcessor,
    DaVinciMagiHumanT2VProcessor,
    DaVinciMagiHumanI2VProcessor,
    SCAIL2ImageToVideoProcessor,
    Vista4DVideoToVideoProcessor,
    DomainShuttleImageToVideoProcessor,
    InSpatioWorldJobProcessor,
    ErnieImageProcessor,
    Ideogram4ImageProcessor,
    PiDImageUpscaleProcessor,
    TeleStyleV2Processor,
    InteractiveWorldJobProcessor,
    MiniMaxH3TextToVideoProcessor,
    MiniMaxH3ImageToVideoProcessor,
)

__all__ = [
    "BaseJobProcessor",
    "VideoOutputHandler",
    "AudioOutputHandler",
    "ImageOutputHandler",
    "ComfyUIProcessor",
    "WAN22TextToVideoJobProcessor",
    "WAN22ImageToVideoJobProcessor",
    "ImageToVideoFromLastFrameJobProcessor",
    "WAN22TextToVideoWan2GPProcessor",
    "WAN22ImageToVideoWan2GPProcessor",
    "ImageToVideoFromLastFrameWan2GPProcessor",
    "LTX23TextToVideoWan2GPProcessor",
    "LTX23ImageToVideoWan2GPProcessor",
    "LTX2TrainerI2VLoraProcessor",
    "LTX2PipelinesI2VLoraProcessor",
    "LTX2PipelinesTextToVideoProcessor",
    "VideoUpscalerJobProcessor",
    "SparkVSRUpscalerJobProcessor",
    "TurboDiffusionT2VJobProcessor",
    "TurboDiffusionI2VJobProcessor",
    "DreamIDOmniImageToVideoProcessor",
    "StableAudioJobProcessor",
    "AudioXJobProcessor",
    "VibeVoiceJobProcessor",
    "VibeVoiceMultiCloneJobProcessor",
    "DiffRhythmCLIJobProcessor",
    "TextToImageJobProcessor",
    "ZImageTextToImageProcessor",
    "ZImageControlNetProcessor",
    "ZImageInpaintProcessor",
    "QwenImageEditProcessor",
    "QwenImageInpaintProcessor",
    "QwenImageT2IProcessor",
    "QwenImage2512LoraT2IProcessor",
    "LLMJobProcessor",
    "ChatterboxTTSJobProcessor",
    "ChatterboxVoiceCloneJobProcessor",
    "HeartMuLaCLIJobProcessor",
    "AceStepCLIJobProcessor",
    "Qwen3TTSJobProcessor",
    "Qwen3VoiceDesignJobProcessor",
    "Qwen3VoiceCloneJobProcessor",
    "F5TTSJobProcessor",
    "F5VoiceCloneJobProcessor",
    "WavTTSJobProcessor",
    "WavTTSVoiceCloneJobProcessor",
    "DotsTTSJobProcessor",
    "DotsTTSVoiceCloneJobProcessor",
    "ScenemaAudioTTSProcessor",
    "ScenemaAudioVoiceCloneProcessor",
    "DramaboxTTSProcessor",
    "DramaboxVoiceCloneProcessor",
    "QwenImageEditTurboProcessor",
    "QwenImageInpaintTurboProcessor",
    "QwenImageT2ITurboProcessor",
    "FluxKontextEditProcessor",
    "FluxKontextT2IProcessor",
    "Krea2TextToImageProcessor",
    "AnimaTextToImageProcessor",
    "MMAudioJobProcessor",
    "LavaSRJobProcessor",
    "PrismAudioJobProcessor",
    "DaVinciMagiHumanT2VProcessor",
    "DaVinciMagiHumanI2VProcessor",
    "SCAIL2ImageToVideoProcessor",
    "Vista4DVideoToVideoProcessor",
    "DomainShuttleImageToVideoProcessor",
    "InSpatioWorldJobProcessor",
    "ErnieImageProcessor",
    "Ideogram4ImageProcessor",
    "PiDImageUpscaleProcessor",
    "TeleStyleV2Processor",
    "InteractiveWorldJobProcessor",
    "MiniMaxH3TextToVideoProcessor",
    "MiniMaxH3ImageToVideoProcessor",
]
