services:
  pid-zimage-upscaler:
    build:
      context: .
      dockerfile: Dockerfile.pid-zimage-upscaler-16gb
    container_name: pid-zimage-upscaler-16gb
    ports:
      - "8000:8000"
    volumes:
      - ./storage/pid/input:/app/input
      - ./storage/pid/output:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
