version: "3.8"

services:
  yume:
    build:
      context: .
      dockerfile: Dockerfile.yume-16gb
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ./storage:/opt/output
      - ./storage:/opt/input
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
