services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.llm
    container_name: ollama-llm
    ports:
      - "11434:11434"
    volumes:
      - ./storage/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
