services:
  comfyui-stable.audio:
    build:
      context: .
      dockerfile: Dockerfile.stable.audio
    container_name: comfyui-stable.audio-cu128
    ports:
      - "8188:8188"
    volumes:
      - ./storage/ComfyUI/output:/opt/ComfyUI/output
      - ./storage/ComfyUI/input:/opt/ComfyUI/input
      - ./storage/ComfyUI/models/audiogen:/opt/ComfyUI/models/audiogen
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
