services:
  audiox:
    build:
      context: .
      dockerfile: Dockerfile.audiox
    container_name: audiox
    ports:
      - "8000:8000"
    volumes:
      - ./storage/audiox/input:/app/input
      - ./storage/audiox/output:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
